# {{NAME}}

External TypeScript agent project generated by Baldr Agent Builder.

```bash
baldr-agent test
baldr-agent build
baldr-agent publish
```

Builder discovers `baldr.typescript`, embeds `@baldr/agent-sdk` into a
self-contained `.cjs` artifact and publishes immutable role manifests.
Run `baldr-agent version <next-version>` before publishing changed source and
`baldr-agent rollback <version>` to reactivate an earlier local release.
