from __future__ import annotations

import hashlib
import json
import shutil
import time
from pathlib import Path
from typing import Any

from baldr_router.facade_contract import render_facade_prompt
from baldr_router.platforming import normalize_path_for_runtime

HOOK_FILENAME = "baldr-router.generated.kiro.hook"
GENERATED_MARKER = "Generated by baldr-kiro-adapter. Do not edit by hand; regenerate with kiro_install_workspace."
MANAGED_SCHEMA_VERSION = 5


class HookInstallConflict(RuntimeError):
    """Raised when installation would overwrite a user-owned or modified hook."""


def workspace_root(path: str | Path) -> Path:
    root = normalize_path_for_runtime(path)
    if not root.exists():
        raise ValueError(f"Workspace does not exist: {root}")
    if not root.is_dir():
        raise ValueError(f"Workspace is not a directory: {root}")
    return root


def hook_path(root: str | Path) -> Path:
    return workspace_root(root) / ".kiro" / "hooks" / HOOK_FILENAME


def _stable_json(data: Any) -> str:
    return json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _payload_without_hash(payload: dict[str, Any]) -> dict[str, Any]:
    copy = json.loads(json.dumps(payload, ensure_ascii=False))
    meta = copy.get("x-baldr-router")
    if isinstance(meta, dict):
        meta.pop("contentHash", None)
    return copy


def managed_payload_hash(payload: dict[str, Any]) -> str:
    """Hash the managed hook payload, excluding the stored hash itself."""
    return _sha256(_stable_json(_payload_without_hash(payload)))


def _hook_entries(
    *, include_context7_prompt_hook: bool = False
) -> list[dict[str, Any]]:
    shared_run_intent = render_facade_prompt("run")
    hooks: list[dict[str, Any]] = [
        {
            "name": "baldr-run-spec-task-through-baldr-router",
            "description": "Before a Kiro spec task starts, translate it to the shared Baldr run intent.",
            "trigger": "PreTaskExec",
            "action": {
                "type": "agent",
                "prompt": f"""
A Kiro spec task is about to start.

Do not implement it directly. Translate the active spec task into the shared Baldr `run` intent.

{shared_run_intent}

Kiro-specific translation:
- use the current workspace root
- include active task title, details, acceptance criteria, and relevant requirements.md/design.md/tasks.md context in the task or extra_context
- infer context7_libraries only when package files, imports, or task wording make them clear
- after Baldr returns, inspect the diff and run relevant tests/lint/typecheck/build
- mark the Kiro task complete only when verification passes

Do not create direct provider-to-provider conversations. Baldr owns that dialogue.
""".strip(),
            },
            "timeout": 0,
            "enabled": True,
        }
    ]

    if include_context7_prompt_hook:
        hooks.append(
            {
                "name": "baldr-prefer-context7-for-library-docs",
                "description": "Use optional Context7 enrichment through Baldr when current library docs materially improve correctness.",
                "trigger": "UserPromptSubmit",
                "matcher": "(?i)(docs|documentation|library|framework|sdk|api|context7|migration|breaking change)",
                "action": {
                    "type": "agent",
                    "prompt": """
Use Baldr Router for documentation enrichment. Context7 is optional and must remain behind the router.

Do not ask for API keys in chat. If Context7 is disabled, continue normally or guide the user through the shared `setup` intent.
""".strip(),
                },
                "timeout": 0,
                "enabled": True,
            }
        )

    return hooks


def generated_hook_json(
    *, include_context7_prompt_hook: bool = False
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "version": "v1",
        "x-baldr-router": {
            "generated": True,
            "schemaVersion": MANAGED_SCHEMA_VERSION,
            "managedFile": HOOK_FILENAME,
            "includeContext7PromptHook": include_context7_prompt_hook,
            "contentHashAlgorithm": "sha256",
            "note": GENERATED_MARKER,
        },
        "hooks": _hook_entries(
            include_context7_prompt_hook=include_context7_prompt_hook
        ),
    }
    payload["x-baldr-router"]["contentHash"] = managed_payload_hash(payload)
    return payload


def write_json_file(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def backup_hook(path: Path, *, reason: str) -> str:
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    backup = path.with_name(f"{path.name}.bak.{timestamp}.{reason}")
    suffix = 1
    while backup.exists():
        backup = path.with_name(f"{path.name}.bak.{timestamp}.{reason}.{suffix}")
        suffix += 1
    shutil.copy2(path, backup)
    return str(backup)


def analyze_hook_file(path: Path) -> dict[str, Any]:
    """Classify an existing generated hook file for safe idempotent onboarding."""
    if not path.exists():
        return {
            "installed": False,
            "state": "missing",
            "generated": False,
            "safe_to_update": True,
        }

    result: dict[str, Any] = {
        "installed": True,
        "path": str(path),
        "safe_to_update": False,
    }

    try:
        raw = path.read_text(encoding="utf-8")
        data = json.loads(raw)
    except Exception as exc:
        result.update(
            {
                "state": "unreadable_or_invalid_json",
                "generated": False,
                "parse_error": str(exc),
                "safe_to_update": False,
            }
        )
        return result

    meta = data.get("x-baldr-router", {})
    generated = isinstance(meta, dict) and meta.get("generated") is True
    hooks = data.get("hooks", [])
    result.update(
        {
            "generated": generated,
            "schema_version": meta.get("schemaVersion")
            if isinstance(meta, dict)
            else None,
            "hooks_count": len(hooks) if isinstance(hooks, list) else None,
            "include_context7_prompt_hook": meta.get("includeContext7PromptHook")
            if isinstance(meta, dict)
            else None,
        }
    )

    if not generated:
        result.update(
            {
                "state": "foreign",
                "reason": "The hook file exists but is not marked as generated by baldr-router.",
                "safe_to_update": False,
            }
        )
        return result

    stored_hash = meta.get("contentHash") if isinstance(meta, dict) else None
    computed_hash = managed_payload_hash(data)
    result.update(
        {
            "stored_hash": stored_hash,
            "computed_hash": computed_hash,
        }
    )

    if not stored_hash:
        result.update(
            {
                "state": "legacy_generated",
                "reason": "Generated by an older baldr-router version without contentHash metadata.",
                "safe_to_update": True,
            }
        )
        return result

    if stored_hash == computed_hash:
        result.update(
            {
                "state": "managed_clean",
                "modified": False,
                "safe_to_update": True,
            }
        )
        return result

    result.update(
        {
            "state": "managed_modified",
            "modified": True,
            "reason": "The hook is marked as generated, but its content hash does not match. It may have been edited manually.",
            "safe_to_update": False,
        }
    )
    return result


def install_workspace_hooks(
    root: str | Path,
    *,
    include_context7_prompt_hook: bool = False,
    git_exclude_generated: bool = True,
    force: bool = False,
    backup_on_update: bool = True,
) -> dict[str, Any]:
    """Create/update generated hooks safely.

    Idempotency behavior:
    - missing hook: create it
    - clean generated hook with same desired content: no-op
    - clean generated hook with stale content/options: update it
    - legacy generated hook without hash metadata: update it, with backup by default
    - user-owned or manually modified hook: skip unless force=True
    """
    r = workspace_root(root)
    p = hook_path(r)
    p.parent.mkdir(parents=True, exist_ok=True)

    desired = generated_hook_json(
        include_context7_prompt_hook=include_context7_prompt_hook
    )
    desired_hash = desired["x-baldr-router"]["contentHash"]
    before = analyze_hook_file(p)
    action = "unknown"
    backup_path: str | None = None
    changed = False

    if before["state"] == "missing":
        write_json_file(p, desired)
        action = "created"
        changed = True
    elif before["state"] == "managed_clean":
        if before.get("computed_hash") == desired_hash:
            action = "unchanged"
        else:
            if backup_on_update:
                backup_path = backup_hook(p, reason="stale")
            write_json_file(p, desired)
            action = "updated_stale"
            changed = True
    elif before["state"] == "legacy_generated":
        if backup_on_update:
            backup_path = backup_hook(p, reason="legacy")
        write_json_file(p, desired)
        action = "updated_legacy"
        changed = True
    elif before["state"] in {
        "managed_modified",
        "foreign",
        "unreadable_or_invalid_json",
    }:
        if not force:
            return {
                "ok": False,
                "changed": False,
                "action": f"skipped_{before['state']}",
                "workspace_root": str(r),
                "hook_path": str(p),
                "desired_hash": desired_hash,
                "status_before": before,
                "reason": "Refusing to overwrite a user-owned or manually modified hook. Re-run with force=True/--force to overwrite after review.",
            }
        if backup_on_update and p.exists():
            backup_path = backup_hook(p, reason="forced")
        write_json_file(p, desired)
        action = f"forced_overwrite_{before['state']}"
        changed = True
    else:  # pragma: no cover
        raise HookInstallConflict(f"Unknown hook state: {before['state']}")

    exclude_result = None
    if git_exclude_generated:
        exclude_result = add_generated_hook_to_git_info_exclude(r)

    after = analyze_hook_file(p)
    result: dict[str, Any] = {
        "ok": True,
        "changed": changed,
        "action": action,
        "workspace_root": str(r),
        "hook_path": str(p),
        "hooks_count": len(desired["hooks"]),
        "desired_hash": desired_hash,
        "status_before": before,
        "status_after": after,
        "git_exclude": exclude_result,
    }
    if backup_path:
        result["backup_path"] = backup_path
    return result


def uninstall_workspace_hooks(
    root: str | Path, *, force: bool = False, backup_on_remove: bool = False
) -> dict[str, Any]:
    """Remove the generated hook file, without deleting user-owned hooks by default."""
    r = workspace_root(root)
    p = hook_path(r)
    before = analyze_hook_file(p)

    if before["state"] == "missing":
        return {
            "ok": True,
            "changed": False,
            "action": "unchanged_missing",
            "workspace_root": str(r),
            "hook_path": str(p),
            "removed": False,
        }

    if (
        before["state"] in {"foreign", "managed_modified", "unreadable_or_invalid_json"}
        and not force
    ):
        return {
            "ok": False,
            "changed": False,
            "action": f"skipped_{before['state']}",
            "workspace_root": str(r),
            "hook_path": str(p),
            "removed": False,
            "status_before": before,
            "reason": "Refusing to remove a user-owned or manually modified hook. Re-run with force=True/--force after review.",
        }

    backup_path = None
    if backup_on_remove and p.exists():
        backup_path = backup_hook(p, reason="removed")
    p.unlink()
    result = {
        "ok": True,
        "changed": True,
        "action": "removed",
        "workspace_root": str(r),
        "hook_path": str(p),
        "removed": True,
        "status_before": before,
    }
    if backup_path:
        result["backup_path"] = backup_path
    return result


def workspace_hooks_status(root: str | Path) -> dict[str, Any]:
    r = workspace_root(root)
    p = hook_path(r)
    status = analyze_hook_file(p)
    status.update(
        {
            "workspace_root": str(r),
            "hook_path": str(p),
        }
    )
    return status


def add_generated_hook_to_git_info_exclude(root: Path) -> dict[str, Any]:
    git_dir = root / ".git"
    if not git_dir.exists() or not git_dir.is_dir():
        return {"ok": True, "changed": False, "reason": "not a git workspace"}

    exclude = git_dir / "info" / "exclude"
    exclude.parent.mkdir(parents=True, exist_ok=True)
    line = f".kiro/hooks/{HOOK_FILENAME}"
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    if line in existing.splitlines():
        return {"ok": True, "changed": False, "path": str(exclude)}
    prefix = "" if not existing or existing.endswith("\n") else "\n"
    exclude.write_text(existing + prefix + line + "\n", encoding="utf-8")
    return {"ok": True, "changed": True, "path": str(exclude)}
